-- Migration 00050: Them gia tri enum moi cho notification_type
-- Ngay: 30/08/2026
--
-- Migration 00048 tach thong bao "dieu chinh diem" thanh 2 loai rieng de
-- client dieu huong dung (tac gia -> "Nhat ky cua toi", nguoi da cham
-- truoc -> "Nhat ky cong tac cua don vi" - trang chi lanh dao). Gia tri
-- 'score_overridden_reviewer_notice' la loai MOI, chua co trong enum
-- notification_type. PHAI la 1 migration RIENG (khong duoc chung transaction
-- voi cho DUNG gia tri nay) - dung quy tac da ap dung cho cac gia tri enum
-- truoc (xem migration 00025, 00027, 00033, 00037).
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'score_overridden_reviewer_notice';
